### ISSUE TITLE
xaxis labels missing

### ISSUE THREAD

**Issue by josephgardner** [bobheadxi/gobenchdata#64]
The x-axis labels appear to be missing. I'm wondering if it's possible to enable the commit hash to appear as the x-axis labels?

*before*

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1297859/173888390-fa436e0b-32d9-4352-9672-88fea4702ce3.png">

*after*

<img width="673" alt="image" src="https://user-images.githubusercontent.com/1297859/173888680-9a20287f-f163-48f3-affe-72d953809359.png">

**Comment by bobheadxi** [comment]
Hey @josephgardner ! You can currently see the commit hash already by hovering over the chart in the latest version of `gobenchdata web`:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/23356519/174936491-55c2d94b-35d4-4203-890b-13986d002cbd.png">

The omission of the commit hash in the x-axis is intentional, because at a glance I think it adds unnecessary clutter, especially when each chart can display multiple benchmarks that need a legend (e.g. the screenshot)

**Comment by josephgardner** [comment]
Fair enough. Thanks for the prompt reply!

One counterargument is that with multiple graphs, it would be easier to correlate spikes if the commit hash was visible. Otherwise you have to hover over each graph separately to see if they all correspond to the same code change. 

Also, our benchmark names are fairly long due to [sub-tests](https://go.googlesource.com/proposal/+/master/design/14313-benchmark-format.md#benchmark-name-configuration) (e.g. `BenchmarkEncode/text=digits/level=default/size=1e4-8`) so the tooltip has a tendency to cover the entire graph making it slightly difficult see your mouse while hovering.
